### ISSUE TITLE
problem with import

### ISSUE THREAD

**Issue by sazearte** [tobspr/P3DFramework#3]
i have an error with master version:

    from core.RSCoreModules import TerrainMeshRenderer
ImportError: No module named core.RSCoreModules

if i replace from core.RSCoreModules by:  from Core.RSCoreModules
i have this error:

[!!!] RenderPipeline          The render pipeline no longer takes the ShowBase argument as constructor parameter. Please have a look at the 00-Loading the pipeline sample to see how to initialize the pipeline properly.

**Comment by tobspr** [comment]
Yeah its a bit outdated, I am basically waiting until rdb accepts my ShaderTerrainMesh patch so I can rewrite it.

**Comment by sazearte** [comment]
OK thanks

**Comment by tobspr** [comment]
I added a sample to the Render PIpeline how to use the Shader Terrain Mesh You can find it here: https://github.com/tobspr/RenderPipeline-Samples/tree/master/08-Terrain

You will need a recent Panda3D build to run it.

I'll delete this repository since the code in here is now obsolete, so don't wonder about that.
